services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - BREVO_API_KEY=${BREVO_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SENDER_NAME=${SENDER_NAME}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./:/app
